services:
  frontend:
    build: .
    user: 'node'
    environment:
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Finland/Helsinki
    # commented out to not make the file required until there's actually use for it
    # env_file:
    #   - .env
    restart: unless-stopped
    ports:
      - 3000:3000
